version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-bookstore
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=bookstore
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared-network

  user-service:
    build: 
      context: .
      dockerfile: ./users/Dockerfile
    container_name: user-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=bookstore
      - MONGODB_COLLECTION=users
    ports:
      - "50051:50051"
    volumes:
      - ./proto-repo:/app/proto-repo
    networks:
      - shared-network
    depends_on:
      - mongodb

  book-service:
    build: 
      context: .
      dockerfile: ./books/Dockerfile
    container_name: book-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=bookstore
      - MONGODB_COLLECTION=books
    ports:
      - "50052:50052"
    volumes:
      - ./proto-repo:/app/proto-repo
    networks:
      - shared-network
    depends_on:
      - mongodb

  borrow-service:
    build: 
      context: .
      dockerfile: ./borrow/Dockerfile
    container_name: borrow-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=bookstore
      - MONGODB_COLLECTION=borrow
    ports:
      - "50053:50053"
    volumes:
      - ./proto-repo:/app/proto-repo
    networks:
      - shared-network
    depends_on:
      - mongodb

  gateway-service:
    build: 
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway-service
    restart: always
    environment:
      - USER_SERVICE_URL=user-service:50051
      - BOOK_SERVICE_URL=book-service:50052
      - BORROW_SERVICE_URL=borrow-service:50053
    ports:
      - "8080:8080"
    volumes:
      - ./proto-repo:/app/proto-repo
    networks:
      - shared-network
    depends_on:
      - user-service
      - book-service
      - borrow-service

volumes:
  mongodb_data: